### ISSUE TITLE
issues with chapter 6

### ISSUE THREAD

**Issue by AbhimanyuAryan** [PacktPublishing/Julia-Web-Development-with-Genie#2]
missing closing tag with array: https://github.com/PacktPublishing/Julia-Web-Development-with-Genie/blob/88d239fb5ec1178d2847a7378ce39350003d7443/Chapter6/TodoMVC/compiled/packages.jl#L9

Logging have some issues. Crashes.....need to comment it: https://github.com/PacktPublishing/Julia-Web-Development-with-Genie/blob/88d239fb5ec1178d2847a7378ce39350003d7443/Chapter6/TodoMVC/config/initializers/logging.jl#L29

I think it's a know issue :https://github.com/PacktPublishing/Julia-Web-Development-with-Genie/blob/88d239fb5ec1178d2847a7378ce39350003d7443/Chapter6/TodoMVC/config/env/prod.jl#L14-L17 

--- causes error I think it's solved with newer genie version. Adrian told either remove this or update Genie: https://github.com/GenieFramework/ScoringEngineApp/blob/master/config/env/prod.jl  (need to confirm and if that's the case update Project.toml)

**Comment by AbhimanyuAryan** [comment]
I think `initialize_logging()` should be `Genie.Logger.initialize_logging()` from what other users reported in discord

**Comment by Ivo-Balbaert** [comment]
corrected
