### ISSUE TITLE
Chapter 7 failing test 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [PacktPublishing/Julia-Web-Development-with-Genie#3]
Added in review but for easy formatting and follow up added it here too. Looks like this line is blowing up

https://github.com/PacktPublishing/Julia-Web-Development-with-Genie/blob/060f5924d22a7972c87409f3318991610a71f832/Chapter7/TodoMVC/test/runtests.jl#L15

```
[01:10:45] ~\..\..\..\test on main ❯ julia --project .\runtests.jl
  Activating project at `C:\Users\aryan\Julia-Web-Development-with-Genie\Chapter7\TodoMVC`
ERROR: LoadError: Couldn't find a Genie app file in .. -- make sure you have one of bootstrap.jl, routes.jl or app.jl
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:35
 [2] loadapp(path::String; autostart::Bool, dbadapter::Nothing, context::Module)
   @ Genie C:\Users\aryan\.julia\packages\Genie\bTQCj\src\Genie.jl:108
 [3] loadapp(path::String)
   @ Genie C:\Users\aryan\.julia\packages\Genie\bTQCj\src\Genie.jl:96
 [4] top-level scope
   @ C:\Users\aryan\Julia-Web-Development-with-Genie\Chapter7\TodoMVC\test\runtests.jl:15
in expression starting at C:\Users\aryan\Julia-Web-Development-with-Genie\Chapter7\TodoMVC\test\runtests.jl:15
```

**Comment by AbhimanyuAryan** [comment]
aah ok looks like this `push!` messed up 

should push ` "C:\\Users\\aryan\\Documents\\TodoMVC\\src"` instead of ` "C:\\Users\\aryan\\Documents\\src"`

<img width="850" alt="loadpath" src="https://user-images.githubusercontent.com/8083613/196055699-4bdbe520-3b9f-4240-9d4b-790ec79ca59b.png">

**Comment by AbhimanyuAryan** [comment]
some debugging

```julia-repl
[01:54:34] ~\..\..\..\test on main ❯ julia --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.2 (2022-09-29)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> ENV["GENIE_ENV"] = "test"
"test"

julia> push!(LOAD_PATH, abspath(normpath(joinpath("..", "src"))))
4-element Vector{String}:
 "@"
 "@v#.#"
 "@stdlib"
 "C:\\Users\\aryan\\Julia-Web-Development-with-Genie\\Chapter7\\TodoMVC\\src"

julia> cd("..")

julia> pwd()
"C:\\Users\\aryan\\Julia-Web-Development-with-Genie\\Chapter7\\TodoMVC"

julia> using Pkg

julia> Pkg.activate(".")
  Activating project at `C:\Users\aryan\Julia-Web-Development-with-Genie\Chapter7\TodoMVC`

julia> using Genie

julia> pwd()
"C:\\Users\\aryan\\Julia-Web-Development-with-Genie\\Chapter7\\TodoMVC"

julia> Genie.loadapp("..")
ERROR: Couldn't find a Genie app file in .. -- make sure you have one of bootstrap.jl, routes.jl or app.jl
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:35
 [2] loadapp(path::String; autostart::Bool, dbadapter::Nothing, context::Module)
   @ Genie C:\Users\aryan\.julia\packages\Genie\bTQCj\src\Genie.jl:108
 [3] loadapp(path::String)
   @ Genie C:\Users\aryan\.julia\packages\Genie\bTQCj\src\Genie.jl:96
 [4] top-level scope
   @ REPL[9]:1

julia> Genie.loadapp(".")


 ██████╗ ███████╗███╗   ██╗██╗███████╗    ███████╗
██╔════╝ ██╔════╝████╗  ██║██║██╔════╝    ██╔════╝
██║  ███╗█████╗  ██╔██╗ ██║██║█████╗      ███████╗
██║   ██║██╔══╝  ██║╚██╗██║██║██╔══╝      ╚════██║
╚██████╔╝███████╗██║ ╚████║██║███████╗    ███████║
 ╚═════╝ ╚══════╝╚═╝  ╚═══╝╚═╝╚══════╝    ╚══════╝

| Website  https://genieframework.com
| GitHub   https://github.com/genieframework
| Docs     https://genieframework.com/docs
| Discord  https://discord.com/invite/9zyZbD6J7H
| Twitter  https://twitter.com/essenciary

Active env: TEST

Running post load hooks ✅┌ Info: 2022-10-17 01:57:47 CREATE TABLE `schema_migrations` (
│       `version` varchar(30) NOT NULL DEFAULT '',
│       PRIMARY KEY (`version`)
└     )
[ Info: 2022-10-17 01:57:47 SELECT version FROM schema_migrations ORDER BY version DESC

Ready!


julia>
```

**Comment by saurabhk710** [comment]
Hey @AbhimanyuAryan ! 
I changed the line to this Genie.loadapp(".") still getting this what this would be?
![image](https://user-images.githubusercontent.com/74169155/196644827-01519fda-5bab-44e8-b48b-73c0d91f25b2.png)

**Comment by AbhimanyuAryan** [comment]
@saurabhk710 are you getting an error with what's inside the book? 

The original content??

**Comment by saurabhk710** [comment]
@AbhimanyuAryan 
no I altered this line  as you mentioned earlier
![image](https://user-images.githubusercontent.com/74169155/196657658-7a3a6151-c91e-4299-939d-4a0a907bf138.png)

**Comment by AbhimanyuAryan** [comment]
@saurabhk710 please check on original code if it works. Then discard review for this. Thanks. Ivo mentioned that 

`Genie.loadapp("..")` works fine on his machine

**Comment by Ivo-Balbaert** [comment]
Here is the complete output of this command on my machine, everything works fine:

D:\Julia_Docs\Book\Julia-Web-Development-with-Genie\Chapter7\TodoMVC\test>julia --project runtests.jl
  Activating project at `D:\Julia_Docs\Book\Julia-Web-Development-with-Genie\Chapter7\TodoMVC`


 ██████╗ ███████╗███╗   ██╗██╗███████╗    ███████╗
██╔════╝ ██╔════╝████╗  ██║██║██╔════╝    ██╔════╝
██║  ███╗█████╗  ██╔██╗ ██║██║█████╗      ███████╗
██║   ██║██╔══╝  ██║╚██╗██║██║██╔══╝      ╚════██║
╚██████╔╝███████╗██║ ╚████║██║███████╗    ███████║
 ╚═════╝ ╚══════╝╚═╝  ╚═══╝╚═╝╚══════╝    ╚══════╝

| Website  https://genieframework.com
| GitHub   https://github.com/genieframework
| Docs     https://genieframework.com/docs
| Discord  https://discord.com/invite/9zyZbD6J7H
| Twitter  https://twitter.com/essenciary

Active env: TEST

Running post load hooks ✅┌ Info: 2022-10-19 20:05:58 CREATE TABLE `schema_migrations` (
│       `version` varchar(30) NOT NULL DEFAULT '',
│       PRIMARY KEY (`version`)
└     )
[ Info: 2022-10-19 20:05:59 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-19 20:05:59 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-19 20:05:59 CREATE TABLE users (id INTEGER PRIMARY KEY , username TEXT  , password TEXT  , name TEXT  , email TEXT  )
[ Info: 2022-10-19 20:05:59 CREATE  INDEX users__idx_username ON users (username)
[ Info: 2022-10-19 20:05:59 INSERT INTO schema_migrations VALUES ('2019052410085235')
[ Info: 2022-10-19 20:05:59 Executed migration CreateTableUsers up
[ Info: 2022-10-19 20:05:59 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-19 20:06:00 CREATE TABLE todos (id INTEGER PRIMARY KEY , todo TEXT  , completed BOOLEAN  DEFAULT false  )
[ Info: 2022-10-19 20:06:00 CREATE  INDEX todos__idx_completed ON todos (completed)
[ Info: 2022-10-19 20:06:00 INSERT INTO schema_migrations VALUES ('2022052910095674')
[ Info: 2022-10-19 20:06:00 Executed migration CreateTableTodos up
[ Info: 2022-10-19 20:06:00 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-19 20:06:00 ALTER TABLE todos ADD user_id INTEGER
[ Info: 2022-10-19 20:06:00 CREATE  INDEX todos__idx_user_id ON todos (user_id)
[ Info: 2022-10-19 20:06:00 INSERT INTO schema_migrations VALUES ('2022092410051450')
[ Info: 2022-10-19 20:06:00 Executed migration AddColumnUserIdToTodos up
[ Info: 2022-10-19 20:06:00 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-19 20:06:03 SELECT COUNT(*) AS __cid FROM "users" WHERE username = 'testuser'
[ Info: 2022-10-19 20:06:03 SELECT COUNT(*) AS __cid FROM "users" WHERE email = 'testuser@test.test'
[ Info: 2022-10-19 20:06:03 INSERT  INTO users ("username", "password", "name", "email") VALUES ('testuser', '13d249f2cb4127b40cfa757866850278793f814ded3c587fe5889e889a7a9f6c', 'Test user', 'testuser@test.test')
[ Info: 2022-10-19 20:06:03 ; SELECT CASE WHEN last_insert_rowid() = 0 THEN -1 ELSE last_insert_rowid() END AS LAST_INSERT_ID
[ Info: 2022-10-19 20:06:04 SELECT "users"."id" AS "users_id", "users"."username" AS "users_username", "users"."password" AS "users_password", "users"."name" AS "users_name", "users"."email" AS "users_email" FROM "users" WHERE "id" = 1 ORDER BY users.id ASC
[ Info: 2022-10-19 20:06:04 INSERT INTO schema_migrations VALUES ('2022100112383884')
[ Info: 2022-10-19 20:06:04 Executed migration CreateDefaultUser up

Ready!

  Activating project at `D:\Julia_Docs\Book\Julia-Web-Development-with-Genie\Chapter7\TodoMVC\test`

todos_API_test: ..............................................................................
todos_db_test: .....
todos_integration_test: WARNING: redefinition of constant APP_PORT. This may fail, cause incorrect answers, or produce other errors.
.......
todos_test: .........


Test Summary: | Pass  Total   Time
TodoMVC tests |   99     99  44.1s

**Comment by AbhimanyuAryan** [comment]
@Ivo-Balbaert someone reported this same issue on discord as well. If it works fine then no need

We go ahead and you can discard this issue 

 ![Screenshot_2022-10-20-00-17-29-50_572064f74bd5f9fa804b05334aa4f912.jpg](https://user-images.githubusercontent.com/8083613/196778153-12fb7190-1132-4aa7-bfdf-115a1e427211.jpg)

**Comment by Ivo-Balbaert** [comment]
Strangely enough Genie.loadapp("..") works for me for Chapter 7, but for Chapter 8 I have to change it to Genie.loadapp() to make it work.

**Comment by saurabhk710** [comment]
Hey 

@Ivo-Balbaert  @AbhimanyuAryan 
really strange  Genie.loadapp(".") works for me too @AbhimanyuAryan 
C:\Users\saurabhk\Downloads\Julia-Web-Development-with-Genie-main\Julia-Web-Development-with-Genie-main\Chapter7\TodoMVC\test>julia --project runtests.jl
  Activating project at `C:\Users\saurabhk\Downloads\Julia-Web-Development-with-Genie-main\Julia-Web-Development-with-Genie-main\Chapter7\TodoMVC`


 ██████╗ ███████╗███╗   ██╗██╗███████╗    ███████╗
██╔════╝ ██╔════╝████╗  ██║██║██╔════╝    ██╔════╝
██║  ███╗█████╗  ██╔██╗ ██║██║█████╗      ███████╗
██║   ██║██╔══╝  ██║╚██╗██║██║██╔══╝      ╚════██║
╚██████╔╝███████╗██║ ╚████║██║███████╗    ███████║
 ╚═════╝ ╚══════╝╚═╝  ╚═══╝╚═╝╚══════╝    ╚══════╝

| Website  https://genieframework.com
| GitHub   https://github.com/genieframework
| Docs     https://genieframework.com/docs
| Discord  https://discord.com/invite/9zyZbD6J7H
| Twitter  https://twitter.com/essenciary

Active env: TEST

Running post load hooks ✅┌ Info: 2022-10-20 11:10:49 CREATE TABLE `schema_migrations` (
│       `version` varchar(30) NOT NULL DEFAULT '',
│       PRIMARY KEY (`version`)
└     )
[ Info: 2022-10-20 11:10:50 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-20 11:10:50 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-20 11:10:51 CREATE TABLE users (id INTEGER PRIMARY KEY , username TEXT  , password TEXT  , name TEXT  , email TEXT  )
[ Info: 2022-10-20 11:10:51 CREATE  INDEX users__idx_username ON users (username)
[ Info: 2022-10-20 11:10:51 INSERT INTO schema_migrations VALUES ('2019052410085235')
[ Info: 2022-10-20 11:10:51 Executed migration CreateTableUsers up
[ Info: 2022-10-20 11:10:51 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-20 11:10:51 CREATE TABLE todos (id INTEGER PRIMARY KEY , todo TEXT  , completed BOOLEAN  DEFAULT false  )
[ Info: 2022-10-20 11:10:51 CREATE  INDEX todos__idx_completed ON todos (completed)
[ Info: 2022-10-20 11:10:51 INSERT INTO schema_migrations VALUES ('2022052910095674')
[ Info: 2022-10-20 11:10:51 Executed migration CreateTableTodos up
[ Info: 2022-10-20 11:10:51 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-20 11:10:51 ALTER TABLE todos ADD user_id INTEGER
[ Info: 2022-10-20 11:10:51 CREATE  INDEX todos__idx_user_id ON todos (user_id)
[ Info: 2022-10-20 11:10:51 INSERT INTO schema_migrations VALUES ('2022092410051450')
[ Info: 2022-10-20 11:10:51 Executed migration AddColumnUserIdToTodos up
[ Info: 2022-10-20 11:10:51 SELECT version FROM schema_migrations ORDER BY version DESC
[ Info: 2022-10-20 11:10:55 SELECT COUNT(*) AS __cid FROM "users" WHERE username = 'testuser'
[ Info: 2022-10-20 11:10:55 SELECT COUNT(*) AS __cid FROM "users" WHERE email = 'testuser@test.test'
[ Info: 2022-10-20 11:10:55 INSERT  INTO users ("username", "password", "name", "email") VALUES ('testuser', '13d249f2cb4127b40cfa757866850278793f814ded3c587fe5889e889a7a9f6c', 'Test user', 'testuser@test.test')
[ Info: 2022-10-20 11:10:55 ; SELECT CASE WHEN last_insert_rowid() = 0 THEN -1 ELSE last_insert_rowid() END AS LAST_INSERT_ID
[ Info: 2022-10-20 11:10:55 SELECT "users"."id" AS "users_id", "users"."username" AS "users_username", "users"."password" AS "users_password", "users"."name" AS "users_name", "users"."email" AS "users_email" FROM "users" WHERE "id" = 1 ORDER BY users.id ASC
[ Info: 2022-10-20 11:10:56 INSERT INTO schema_migrations VALUES ('2022100112383884')
[ Info: 2022-10-20 11:10:56 Executed migration CreateDefaultUser up

Ready!

  Activating project at `C:\Users\saurabhk\Downloads\Julia-Web-Development-with-Genie-main\Julia-Web-Development-with-Genie-main\Chapter7\TodoMVC\test`

todos_API_test: WARNING: replacing module CreateTableUsers.
WARNING: replacing module CreateTableTodos.
WARNING: replacing module AddColumnUserIdToTodos.
WARNING: replacing module CreateDefaultUser.
..............................................................................WARNING: replacing module CreateDefaultUser.
WARNING: replacing module AddColumnUserIdToTodos.
WARNING: replacing module CreateTableTodos.
WARNING: replacing module CreateTableUsers.

todos_db_test: WARNING: replacing module CreateTableUsers.
WARNING: replacing module CreateTableTodos.
WARNING: replacing module AddColumnUserIdToTodos.
WARNING: replacing module CreateDefaultUser.
.....WARNING: replacing module CreateDefaultUser.
WARNING: replacing module AddColumnUserIdToTodos.
WARNING: replacing module CreateTableTodos.
WARNING: replacing module CreateTableUsers.

todos_integration_test: WARNING: redefinition of constant APP_PORT. This may fail, cause incorrect answers, or produce other errors.
WARNING: replacing module CreateTableUsers.
WARNING: replacing module CreateTableTodos.
WARNING: replacing module AddColumnUserIdToTodos.
WARNING: replacing module CreateDefaultUser.
.......WARNING: replacing module CreateDefaultUser.
WARNING: replacing module AddColumnUserIdToTodos.
WARNING: replacing module CreateTableTodos.
WARNING: replacing module CreateTableUsers.

todos_test: .........


Test Summary: | Pass  Total   Time
TodoMVC tests |   99     99  52.7s

**Comment by AbhimanyuAryan** [comment]
I think it has to do something with Genie Version being used

If the project.toml has `Genie` in `compat` then ignore this feedback and we can keep `loadapp(..)` for this chapter
